### PR TITLE
Updated required pollination version to 1.46.0

### LINKED ISSUE #191: Update pollination requirement to 1.46
#### Description:

There are a few bug fixes in pollination 1.46 that are needed, so we are updating the pollination version. This change necessitates some changes to the python code, and in general a lot of testing of that code which will be done throughout the 7.2 milestone.

image
image

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #191 

updated required pollination version to 1.46.0, and made change to fix issue caused by the upgrade.

### Test files

[LBT_Plots.zip](https://github.com/BHoM/LadybugTools_Toolkit/files/15039437/LBT_Plots.zip)

### Changelog

- Updated required Pollination version to 1.46.0

### Additional comments

The test file provided gives a general cover of what a user might expect (component/grasshopper-wise), though more thorough testing will be required throughout the following milestone

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Review by tg359 — APPROVED** [review]
I've tested these changes on my machine and they don't cause an issue - everything working as expected.

**Review by CKBoulter — APPROVED** [review]
Installed and tested using previous scripts. All working fine. 

Note: When running psychometrics, warning "FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead." appears.

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling 
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
