### PR TITLE
Fix installer build by shortening file path

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes installer builds by reducing the file path length for the affected file.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral-checks on: ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: ready-to-merge

**Review by rboulton-BH — APPROVED** [review]
No changes made to code, only the filename has changed. Ganz genehmigt!

**Pull request merged**
