### PR TITLE
Updates to simulations, external comfort, and plots

### LINKED ISSUE #98: Adjusting figsize of plots
#### Description:

Hi team, I find the default figsizes are something that I'm regularly interested in adjusting (and the ones on the current climate dashboard don't particularly work well for A4 reports). 

I'm sure there's a way to handle this easily with Matplotlib, but for those of us less familiar with it, please could we expose figsize as a variable in the plot methods? 

E.g. this 
image

Welcome thoughts on if there's a better approach for this. 

Cheers,

### LINKED ISSUE #100: Option to hide analysis period from title in utci_comfort_band_comparison
Currently, the `describe_analysis_period(analysis_periods)` is always appended to the user-provided title. Sometimes, we don't want this to happen. 

Provide an option to not include the analysis period string as part of the title.

### LINKED ISSUE #104: utci_comfort_band_comparison plot: Display hours
Currently, this plot prints the percentage of overall time for each analysis band. It would be useful to have an option to instead/in addition show the number of hours that this is equivalent to. (e.g. if there is moderate heat stress 50% of the time, then it would be nice to see this shown as 4380 hours.)  

image

### PR DESCRIPTION
**Pull request by jamesramsden-bh**
Includes some refactoring off the back of several projects within the python src folder. Test against the usual test batch file within the Python folder. 

Closes #98
Closes #100 
Closes #104

### CODE REVIEW

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Have run through the code with @jamesramsden-bh on a call and all is in line with his testing of work done in collaboration with @tg359 - happy to approve to deploy to unblock them.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Pull request merged**
