### PR TITLE
Upgrade to .NetStandard 2.0

### LINKED ISSUE #123: Upgrade to .NetStandard2.0
Toolkit is currently in Framework, upgrade to .NetStandard.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #123

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 17999059356

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FelixMallinder-BH — APPROVED** [review]
Tested and works successfully

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Review by albinber — APPROVED** [review]
Test passed

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests, ready-to-merge

**Pull request merged**
