### PR TITLE
Fix SpatialComfort processing method/s

### LINKED ISSUE #238: SpatialComfort methods got a little broken in previous updates to upstream code
#### Description:

A few method signatures have changed that SpatialComfort relies on. 

I'll use the branch linked to this issue to apply the fixes necessary to get the process working fully on future BHoM installs.

#### Steps to reproduce:

Attempt to run C:\ProgramData\BHoM\Extensions\PythonCode\LadybugTools_Toolkit\tests\test_external_comfort\test_spatial_comfort.py and watch all the errors appear.

#### Expected behaviour:

Errors do not occur!

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #238 

- Method signatures updated in SpatialComfort plotting
- CFD results loading uses try-catch now to handle slightly different format input files
- SpatialComfort checks for available disk space prior to running and warns user if it's a bit low

### Test files

Attempt to run C:\ProgramData\BHoM\Extensions\PythonCode\LadybugTools_Toolkit\tests\test_external_comfort\test_spatial_comfort.py and hope that errors no longer appear.

### CODE REVIEW

**Review by Tom-Kingstone — COMMENTED** [review]
I tested using the unit test script provided (I used the run_tests.bat file in the root of the python source). All tests pass (most importantly the spatial comfort tests pass). Approve on condition that one of the engineers linked is happy with the changes

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Review by CKBoulter — COMMENTED** [review]
Tested using the run_tests.bat file. All passed but one: test_prevailing.

Failure issue:
tests\test_wind.py:184: AssertionError

**Review by CKBoulter — APPROVED** [review]
Previous issue was a local problem. Tested again using run_tests.bat and all passed. Approve changes.

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check unit-tests
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
