### PR TITLE
Fixed bhom_analytics logger

### LINKED ISSUE #204: Nugets produced can't use the bhom_analytics logger properly
#### Description:

when using a nuget from this repo without a full BHoM install, the BHoM logger gets stuck in two places, firstly , the file path C:\ProgramData\BHoM\Logs does not exist, so the logger crashes when trying to record entries. Secondly, the file version for BHoM.dll cannot be retrieved from its normal location.

#### Expected behaviour:

fix by adding a check to see whether the bhom log folder and assemblies directories exist, and if not, create a folder in temp for logs, and don't try to get the file version.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #204 

Removed redundant variables, and added 2 checks:
* Check that the bhom log folder exists, if not change to temp directory and create the directory anew
* Check that the bhom assemblies folder exists, if not, don't try to get the file version of BHoM.dll

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check code
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed code and discussed with @Tom-Kingstone and all good

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
