### PR TITLE
Fixed importing concurrent

### LINKED ISSUE #248: import error for solar.direction_irradiance_matrix
#### Description:

error raised when trying to use the c# wrapper (during beta testing)
`AttributeError: module 'concurrent' has no attribute 'futures'`

fix for this is changing the import to `import concurrent.futures`

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #248 

As in issue

### Test files

The LBT beta test script will be the test - ensure that the `Solar.png` file is created in the same directory as the grasshopper script.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by Tom-Kingstone** [comment]
@BHoMBot check unit-tests
@BHoMBot check serialisation
@BHoMBot check null-handling

**Comment by jamesramsden-bh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
