### PR TITLE
Convert Honeybee+ Surface to Environment objects (Panels/Openings)

### LINKED ISSUE #4: Convert Honeybee surfaces to Environment Panels
As title.

FYI: @MarthaVoul @tg359 @michaelhoehn

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #4 

### Test files
[Available here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/LadybugTools_Toolkit/Issue%204%20-%20HBSrf%20to%20BHoM.gh?csf=1&web=1&e=5cZNso)

### CODE REVIEW

**Comment by tg359** [comment]
Just jumping in here. Are we focusing on HB-Legacy, or including HB+ objects as there is quite a difference between the workflows and data stored in them. I prefer the HB+ stuff as it's a bit more neat, but most workflows currently use the HB-Legacy objects. The HB+ components would more easily convert to/from BHoM directly.

image

**Comment by FraserGreenroyd** [comment]
@tg359 currently doing HB+ objects in this PR. Long term I think it would be good to do both.

I was speaking with Antoine this morning about this further and the LB team are developing up workflows to take LB models into JSON and a C# schema (which we're using as a nuget in this PR ready) to read that JSON and convert to C# objects which will make some of the workflows easier (as you can see from the code, this is basically taking an `IronPython` `dynamic` object and converting it to the BHoM object.

I'm not sure how well this PR would work with the legacy surface, but might be good to try out.

Long term it would be good to plan out the full workflows for this toolkit (in addition to getting something up for installer use and discussion), I'll probably suggest a workshop as we get to the end of the milestone to plan out tasks with @MarthaVoul @michaelhoehn @charliebrookerBH etc. :smile:

**Pull request merged**
