### PR TITLE
Added distance to comfortable plot for review

### PR DESCRIPTION
**Pull request by jamesramsden-bh**
Adds another plot - a simpler version of the utci_distance_to_comfortable.py. PR created for discussion. 

image

Do not merge until merge freeze is lifted in Jan 2023.

### CODE REVIEW

**Review by tg359 — APPROVED** [review]
Tested and this works. In the interest of tidying up our GitHub I'm happy for this to be merged as both me and @jamesramsden-bh know that the visualisation methods are due a rethink in the near future and I don't want to lose this.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on @tg359 review with only the base branch being changed.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Pull request merged**
