### PR TITLE
Fixed test failure due to mismatch in object properties

### PR DESCRIPTION
**Pull request by tg359**
… to avoid failure in passing data between languages

   
### Issues addressed by this PR

Failure in testing of code passed between BHoM/C# and Python where objects hadn't been fully updated to match new schema. Minor fix to ensure that properties can be populated to stop failure in this process.

### Test files

LBT_Tk test script should now function fully, so I'd suggest using that to test as otherwise it returns a failure.

### CODE REVIEW

**Comment by albinber** [comment]
@bhombot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required
@BHoMBot check unit-tests

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed through with @tg359

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
