### PR TITLE
Fixed incorrect file name

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #

fixed incorrect file name, and removed null reference exception.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Code reviewed and aligns with discussion with @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
