### PR TITLE
Adapter: added remaining object serialisation

### LINKED ISSUE #144: Add more ILadybugTools objects to adapter pushing and pulling
#### Description:

Currently, the following objects are not yet supported by the adapter:
- `ExternalComfort`
- `Shelter`
- `SimulationResult`
- `Typology`

Ideally, these would be supported so the adapter can be used in the engine methods - Therefore `To` and `From` BHoM methods should be added to `Convert` in the adapter supporting these.

This issue also covers updating the engine methods to use the adapter for serialisation.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #144 

`ExternalComfort`, `SimulationResult`, `Shelter`, and `Typology` have been added to the adapter to allow conversion to python-readable json, ready to be used in the engine methods.
The adapter can also convert `Point`s to ladybug `Point3D`s, though this isn't accessible other than when converting Shelters.

Also added support for converting multiple objects to json.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix copyright headers ref. 19104709440

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot please could this check for versioning pass?

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Good work @Tom-Kingstone happy to deploy for alpha testing

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 19106541863

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
