### PR TITLE
Updated unit test files

### LINKED ISSUE #75: An error occurred on a unit test
<samp>The following errors have been reported on unit tests in this repository.

**BHoM/LadybugTools_Toolkit\.ci\Datasets\Compute\SimulationId.json**
Unit test set: SimulationId. Author: tgerrish
One or more of the UnitTests failed.
Inner results:
	UnitTest: Method: SimulationId(String epwFile, ILBTMaterial groundMaterial, ILBTMaterial shadeMaterial).
	The UnitTest did not pass.
	Inner results:
		TestData: index: 0
		Execution of the method did not return the expected outputs.
		Inner results:
			02/12/2022 03:27:23
			Data returned for output 0 is an unexpected null.
</samp>

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #75 

Error was due to inclusion of null handling in methods referenced by unit tests, and checks for existence of file/s prior to passing to the Python methods downstream of the C# methods. I've removed the test that references a file as I cannot guarantee that a named file will exist in a specific place on the machine running the unit-tests.

### CODE REVIEW

**Comment by tg359** [comment]
@BHoMBot check versioning
@BHoMBot check code-compliance
@BHoMBot check documentation-compliance
@BHoMBot check dataset-compliance
@BHoMBot check project-compliance
@BHoMBot check copyright-compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by tg359** [comment]
@Bhombot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by tg359** [comment]
@BHoMBot thank-you

**Comment by tg359** [comment]
@BHoMBot thanks

**Comment by tg359** [comment]
@BHoMBot tack

**Comment by tg359** [comment]
tack @BHoMBot

**Review by FraserGreenroyd — APPROVED** [review]
Unit tests are happy

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
