### PR TITLE
External comfort processing vastly improved and analytics implemented

### LINKED ISSUE #54: Speed up post-processing of SpatialResults moisture matrix and UTCI
#### Description:

Slowdown mainly due to large array maths being done in for-loops. Using Numpy properly (mapping processes across like-shaped arrays) should handle this faster, or even trying out something like Dask to better handle the processing of larger-than-memory datasets could work.

### LINKED ISSUE #63: Fix null handling
#### Broken rules:

Fix null handling for following methods:
```
BH.Engine.LadybugTools.Compute.ExternalComfortTypology(String typologyName)
    Error: A NullReferenceException was received from method BH.Engine.LadybugTools.Compute.ExternalComfortTypology(String typologyName).
BH.Engine.LadybugTools.Compute.ExternalComfortMaterial(String materialName)
    Error: A NullReferenceException was received from method BH.Engine.LadybugTools.Compute.ExternalComfortMaterial(String materialName).
BH.Engine.LadybugTools.Compute.EPWtoCustomObject(String epwFile)
    Error: A NullReferenceException was received from method BH.Engine.LadybugTools.Compute.EPWtoCustomObject(String epwFile).
BH.Engine.LadybugTools.Compute.EPWtoCSV(String epwFile)
    Error: A NullReferenceException was received from method BH.Engine.LadybugTools.Compute.EPWtoCSV(String epwFile).
BH.Engine.LadybugTools.Compute.ExternalComfortSimulationResult(String identifier, String epwFile, ExternalComfortMaterial groundMaterial, ExternalComfortMaterial shadeMaterial)
    Error: A NullReferenceException was received from method BH.Engine.LadybugTools.Compute.ExternalComfortSimulationResult(String identifier, String epwFile, ExternalComfortMaterial groundMaterial, ExternalComfortMaterial shadeMaterial).
BH.Engine.LadybugTools.Compute.ExternalComfort(String identifier, String epwFile, ExternalComfortMaterial groundMaterial, ExternalComfortMaterial shadeMaterial, ExternalComfortTypology typology)
    Error: A NullReferenceException was received from method BH.Engine.LadybugTools.Compute.ExternalComfort(String identifier, String epwFile, ExternalComfortMaterial groundMaterial, ExternalComfortMaterial shadeMaterial, ExternalComfortTypology typology).
BH.Engine.LadybugTools.Compute.HBJSONtoGEM(String hbjson)
    Warning: Failed to generate test method BH.Engine.LadybugTools.Compute.HBJSONtoGEM(String hbjson) for null checks because it thew another type of exception.
    Inner results:
        The path is not of a legal form.
BH.Engine.LadybugTools.Compute.GEMtoHBJSON(String gem)
    Warning: Failed to generate test method BH.Engine.LadybugTools.Compute.GEMtoHBJSON(String gem) for null checks because it thew another type of exception.
    Inner results:
        The path is not of a legal form.
```

### LINKED ISSUE #67: Enable direct manipulation of radiation/wind porosity in typologies

### LINKED ISSUE #68: EPW and data collection comparability
#### Description:

It seems I've misplaced some code! I'll find it and add it to the related branch here. It compares different HourlyContinuousDataCollection and EPW objects to visualise differences - as well as creating some methods to give user insight into those differences.

### PR DESCRIPTION
**Pull request by tg359**
### NOTE: Depends on 

https://github.com/BHoM/Versioning_Toolkit/pull/207

### Issues addressed by this PR

Closes #67
Closes #63 
Closes #54 
Closes #68

Many things changed. Most notably the inclusion of **good** analytics which don't add overhead to the processing methods.

### Test files

Prior to testing you'll need to run the `InstallPythonEnv_LBT` method to set-up the Python environment. Afterwards you can compile the code which will move all the Python files where tehy need to go. After this you can also run the unit tests for the Python code by calling this command:
```
"C:\ProgramData\BHoM\Extensions\PythonEnvironments\LadybugTools_Toolkit\Scripts\python.exe" -m pytest "C:\ProgramData\BHoM\Extensions\PythonCode\LadybugTools_Toolkit\src\tests"
```
[LBTToolkit_66.zip](https://github.com/BHoM/LadybugTools_Toolkit/files/10113305/LBTToolkit_66.zip)

### CODE REVIEW

**Comment by tg359** [comment]
@jamesramsden-bh I'll wait until we have a look at this together before running any bot checks, in-case any changes need to be made beforehand.

**Review by jamesramsden-bh — APPROVED** [review]
Individual files not reviewed, but tested functionality as per PR description. GH script and unit tests all passing on my machine.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by tg359** [comment]
@BHoMBot check null-handling

**Comment by tg359** [comment]
@BHoMBot check null-handling

**Comment by tg359** [comment]
@BHoMBot check required

**Comment by tg359** [comment]
@BHoMBot check copyright-compliance

**Comment by tg359** [comment]
@BHoMBot check ready-to-merge

**Review by jamesramsden-bh — APPROVED** [review]
Retested using provided GH script and unit tests, all passing.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
