### PR TITLE
Updated OpenMeteoVariable test script

### LINKED ISSUE #179: Test for OpenMeteoVariable needs updating to stop testing removed variables
#### Description:

The test for OpenMeteoVariable tests `from_string("windgusts_10m")` which was removed. This needs updating to test a different variable with the from_string method.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #179 

replaced `windgusts_10m` with `winddirection_100m`

### Test files

build, then run `run_tests.bat` in ProgramData/BHoM/Extensions/PythonCode/LadybugToolsToolkit

### CODE REVIEW

**Review by tg359 — APPROVED** [review]
Thanks for fixing this @Tom-Kingstone, this will make the pytest pass now.

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
