### PR TITLE
Adapter: made LBT PythonEnvironment a private property

### LINKED ISSUE #171: Adapter: Make python environment a private property
#### Description:

Rather than finding/loading/installing an LBT PythonEnvironment every time an adapter action is executed, it should be done once on instantiation of the adapter, and then the environment should be stored as a private property and accessed when needed.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #171 

Added private `m_environment` property to `LadybugToolsAdapter` and updated usage in execute commands.
Also install BasePythonEnvironment before LBT environment for better UX

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Review by albinber — APPROVED** [review]
Changes look good and tests passed, happy to approve

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed the code and looks good, nice work @Tom-Kingstone

**Pull request merged**
