### PR TITLE
BHoM managed Python virtualenvs

### LINKED ISSUE #55: Modify BHoM code to reference Pollination installer location rather than Food4Rhino location
#### Description:

As we'll likely adopt the Pollination installer means of getting LB code, it would make sense to reference the location Pollination installs all of the software (Program Files/ladybug_tools) instead of the older location (<user>/ladybug_tools).

### LINKED ISSUE #57: Pie chart for UTCI plot
#### Description:

A standard pie chart will be helpful.

### LINKED ISSUE #58: Python_Toolkit-#83-SimplificationAndExternalEnvironments
#### Parent issue(s) or Pull Request(s) causing the changes:

https://github.com/BHoM/Python_Toolkit/tree/Python_Toolkit-%2383-SimplificationAndExternalEnvironments

### PR DESCRIPTION
**Pull request by tg359**
### NOTE: Depends on 
https://github.com/BHoM/Python_Toolkit/pull/85
   
### Issues addressed by this PR

Closes #58
Closes #55 
Closes #57

Handling of Python environments via BHoM rationalised around a base "full" environment, and virtualenvs for any toolkit/project-specific environment that can be pre-defined with custom codebases via a referenced local-package added upon installation.

This PR enables a replicated virtualenv of LadybugTools installed via Pollination.

### Test files

[83.zip](https://github.com/BHoM/LadybugTools_Toolkit/files/9358146/83.zip)

### CODE REVIEW

**Comment by tg359** [comment]
@BHoMBot check required

**Comment by tg359** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check core
@BHoMBot check serialisation

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on @alelom review as commits since then have been versioning and compliance.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 8273485563

**Pull request merged**
