### PR TITLE
Re-implemented GetMaterial and GetTypology methods

### LINKED ISSUE #139: Reimplement loading of predefined Materials and Typology objects
#### Description:

Methods were removed following changes to code, but can now be re-implemented as the means of running them have been sped-up and simplified.

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #139

Following changes to how objects were being constructed, these methods were removed as they were becoming very slow. Now those changes have been optimised they can be re-implemented.

### Test files

Just use the GetMaterial and GetTypology methods.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Comment by tg359** [comment]
@BHoMBot check compliance

**Comment by tg359** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
The code came back, happy with it for now, thanks @tg359

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
