### PR TITLE
Python virtual environment creation fixes and refactor

### PR DESCRIPTION
**Pull request by tg359**
### NOTE: Depends on 

https://github.com/BHoM/Python_Toolkit/pull/107

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Review by jamesramsden-bh — APPROVED** [review]
Reinstalled with corresponding PR for Python TK. Installs successfully. Unit tests and a manual spot check all tested and no problems.

**Review by jamesramsden-bh — APPROVED** [review]
Reconfirming approval after accidentally re-requesting a review from myself...

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: versioning, ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
My changes have been addressed, happy to merge.

**Pull request merged**
