### PR TITLE
Move base plots to Python_Toolkit

### LINKED ISSUE #206: Break out plot generation into base plot types and specific implementations
The LBT_TK plots could do with a bit of a reorganisation. Plots should generally be broken down into two levels:

1) Base plot type (e.g. heat map, pie chart, line graph, histogram...) that take in generic types
2) Implementations of the above to fulfil a specific purpose (e.g. a UTCI heat map) that may take in specific types (e.g. hourly continuous collection with a UTCI header)

This has been partially implemented already, e.g. there is a generic heatmap and a UTCI heatmap. However, there are places where specific implementations have not been broken from the base plot type. E.g. a stacked bar chart can only be found inside the utci_comfort_band_comparison method, which requires hourly continuous collecitons of UTCI-headed data. 

By breaking out these levels and separating concerns, it makes it possible for a user to create a plot using generic types. 

Where possible, try to not change method signatures of existing plots, to help with versioning/back-compatibility. 

cc @tg359

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #206 

Base plots and helper/utility methods have been moved to Python_Toolkit (see the linked PR at the top)
References to python_toolkit have been made where utility and helper methods have been moved, so that the rest of the toolkit and any user scripts do not break, though plots marked private that were moved will have been updated to `python_toolkit.plot.<name-of-plot>` and no longer marked as private.

e.g. 
`from ladybugtools_toolkit.plot._heatmap import heatmap` 
would become
`from python_toolkit.plot.heatmap import heatmap`

### Test files

run the python unit tests to check that nothing is broken.

### Changelog

* Moved python base plot types and some utility methods, see changelog for Python_Toolkit for more information.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance
@BHoMBot check versioning

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer

**Review by jamesramsden-bh — APPROVED** [review]
Tested with unit tests plus some self spot checks. No critical issues preventing merge. Any non-critical issues should have issues raised separately.

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check unit-tests

**Pull request merged**
