### PR TITLE
Cast radiation_porosity and wind_porosity to list(float)

### LINKED ISSUE #200: Shelter radiation_porosity bug when values are mixed floats/ints
To replicate, create a typology where the radiation_porosity type in the first shelter does not match the type of any of the other shelters, e.g.

```
Typology(
        identifier=f"Test Typology",
        shelters=[
            Shelter.from_adjacent_wall(angle=0, radiation_porosity = (0,) * 8760),
            Shelter.from_adjacent_wall(angle=90, radiation_porosity = (0.0,) * 8760),
        ],
        )
```

Then run an ExternalComfort with this typology as an input to a SimulationResult. The ExternalComfort will fail. This is because the numpy stuff under the hood can't handle these mixed types. (Specifically, it fails on line 859 of _shelterbase, because numpy gets the object type from the first shelter on line 855.)

Easiest fix: when constructing the typology, force convert the radiation_porosity to float.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #200 

If the type check for list(float, int) passes, now casts radiation and wind porosity to list(float).

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Review by jamesramsden-bh — APPROVED** [review]
Tested with a typology of mixed ints and floats, external comfort now calculates without raising an error.

**Review by tg359 — APPROVED** [review]
Tested and the issue no longer appears, thanks @Tom-Kingstone.

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
