### PR TITLE
Fixed openmeteo wind speed conversion

### LINKED ISSUE #166: Fix scrape_openmeteo wind speed value conversion
#### Description:

@CKBoulter found a bug with the wind speed conversion which resulted in values being kept as km/h instead of m/s - meaning downstream processes broke a little.

### PR DESCRIPTION
**Pull request by tg359**
### Issues addressed by this PR

Closes #166

### CODE REVIEW

**Review by CKBoulter — APPROVED** [review]
Updates fix conversion issue closing #166 and #167. Pulled latest branch, ensure all cached data is removed from pathways. Reran code and now results are correctly converted from km/h to m/s.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
