### PR TITLE
Updated nuspec to include python code files

### LINKED ISSUE #197: Update nuspec file to include PythonCode as content
Update the nuspec file so that when installing nugets the python code is included and copied to output on build, similar to the post-build event for `LadybugTools_Engine`:

```
<?xml version="1.0" encoding="utf-8"?>
<package>
  <metadata>
    <id>BHoM.Interop.LadybugTools</id>
    <version></version>
    <authors>BHoM</authors>
    <projectUrl>https://github.com/BHoM/LadybugTools_Toolkit</projectUrl>
    <license type="file">licence.txt</license>
    <icon>icon.png</icon>
    <readme>readme.md</readme>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Interact with Ladybug Tools via BHoM</description>
    <releaseNotes></releaseNotes>
    <copyright></copyright>
    <tags>BHoM engine aec LadyBug LadyBugTools</tags>
    <title></title>
    <dependencies>
      <group targetFramework="netstandard2.0">
        <dependency id="NETStandard.Library" version="2.0.3" />
        <dependency id="Microsoft.CSharp" version="4.7.0" />
      </group>
      <contentFiles>
	<files include="any\any\PythonCode\**\*.*" buildAction="Content" copyToOutput="true" flatten="false"/>
        <files include="any\any\PythonEnvironment\**\*" buildAction="Content" copyToOutput="true" flatten="false"/>
      </contentFiles>
    </dependencies>
  </metadata>
  <files>
    <file src="licence/licence.txt" target="" />
    <file src="images/icon.png" target="" />
    <file src="docs/readme.md" target="" />
    <!--lib\**\* is a workaround for contentfiles not including dll files-->
    <file src="lib\**\*" target="lib" />
    <file src="C:\ProgramData\BHoM\Extensions\PythonCode\LadybugTools_Toolkit\src\ladybugtools_toolkit\bhom\wrapped\**\*.*" exclude="**\__pycache__\*;**\docs\**\*" target="contentFiles\any\any\PythonCode\LadybugTools_Toolkit\src\ladybugtools_toolkit\bhom\wrapped"/>
    <file src="C:\ProgramData\BHoM\Extensions\PythonCode\LadybugTools_Toolkit\src\**\*.*" exclude="**\__pycache__\*;**\docs\**\*" target="contentFiles\any\any\PythonEnvironment\Lib\site-packages" />
  </files>
</package>
```

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #197

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — APPROVED** [review]
It's a shame it has to be so hard coded, but this fixes the immediate issue

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Pull request merged**
