### PR TITLE
Removing apostrophe in GetMaterial description

### LINKED ISSUE #78: Remove apostrophe in GetMaterial description
In Engine\Query\GetMaterial.cs line 36 is the following:

`        [Description("Get a material object from it's Enum.")]`

Replace "it's" with "its".

### PR DESCRIPTION
**Pull request by kprusicka**
### Issues addressed by this PR

Closes #78 

Apostrophe removed.

### CODE REVIEW

**Comment by kprusicka** [comment]
@BHoMBot Check required

**Review by FraserGreenroyd — APPROVED** [review]
Code reviewed and meets the objective

**Comment by FraserGreenroyd** [comment]
@BHoMBot check unit-tests
@BHoMBot check dataset-compliance
@BHoMBot copyright-compliance
@BHoMBot ready-to-merge

**Comment by kprusicka** [comment]
@BHoMBot Check copyright-compliance
@BHoMBot Check dataset-compliance
@BHoMBot Check unit_tests

**Comment by kprusicka** [comment]
Thank you @BHoMBot

**Pull request merged**
