### PR TITLE
Updated .json

### LINKED ISSUE #49: Update Json for beta release
#### Description:
Update the Json on main, so that users can link to this Json for Beta 5.1. This replaces the existing Json on main, which currently causes the environment install to fail.

### PR DESCRIPTION
**Pull request by jamesramsden-bh**
### Issues addressed by this PR

Closes #49 
Updated Json file added to allow users to run LB TK env installer by linking to and copying from this file.

### CODE REVIEW

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Comment by jamesramsden-bh** [comment]
@BHoMBot check copyright-compliance

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
Have reviewed the code, warning messages make sense and are appropriate.
Have reviewed the accompanying wiki page, made slight wording changes in discussion with @jamesramsden-bh .
Both LGTM.

**Pull request merged**
