### PR TITLE
Move engine methods utilising serialisation to Adapter Execute

### LINKED ISSUE #143: Update Engine methods to use adapter for serialisation
#### Description:

Use the adapter pull and push methods created in #142 for converting ladybug objects to and from JSON to be used by python.

At the moment, there is only one method that uses objects supported by the adapter, so this issue only covers `GetMaterial`, but this can be an example for future use on coding with the new adapter methods.

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #143 

The engine methods: `GetMaterial`, `GetTypology`, `SimulationResult`, and `ExternalComfort` have been converted to adapter methods callable by `Execute` commands, that now utilise the LadybugToolsAdapter serialisation methods.

### Test files

[LBT_Tests.zip](https://github.com/BHoM/LadybugTools_Toolkit/files/13499391/LBT_Tests.zip)
Ensure the EPW file path is valid, then set toggles to True in order (`GetMaterial`, `GetTypology`, `SimulationResult`, `ExternalComfort`) and wait for them to finish computing, check for any warnings or errors, and finally check that the returning objects contain data in each property - This is testing whether the serialiser is pulling and pushing correctly.

### Additional comments

You must have pollination version 1.35.14 installed for these components to work - the methods check for this.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
As discussed on a call, Engine shouldn't use Adapter - @Tom-Kingstone will take a look at using Execute options instead and update the PR accordingly tomorrow/later int he week 😄

**Comment by Tom-Kingstone** [comment]
@BHoMBot fix copyright headers ref. 19180266457

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check core

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
I think the adapter references, of which only `Adapter_oM` is needed, should have gone into the oM project, not the engine project?

**Comment by Tom-Kingstone** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
It's not great with the global variable but as discussed offline, not a lot we can do right now, so we'll merge this as a working solution for alpha testing and we can have more chats on improvements @Tom-Kingstone

**Comment by Tom-Kingstone** [comment]
@BHoMBot check installer
@BHoMBot check unit-tests
@BHoMBot check ready-to-merge

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
