### PR TITLE
Fixed deprecation warnings for python unit tests

### LINKED ISSUE #208: Warnings while running python unit tests
#### Broken rules:

some warnings when running python unit-tests, 
```
tests\test_ladybug_extension\test_datacollection.py:14: 1 warning
tests/test_external_comfort/test_shelter.py: 14 warnings
tests/test_helpers.py: 3 warnings
tests/test_plot.py: 2 warnings
tests/test_solar.py: 4 warnings
  FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.

tests/test_external_comfort/test_externalcomfort.py: 1 warning
tests/test_ladybug_extension/test_groundtemperature.py: 2 warnings
tests/test_plot.py: 10 warnings
  FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
```

#### Suggestions to restore compliance:

This is due to using "T" and "H" when using `pd.date_range` in the `freq` kwarg. e.g: in shelter.py line 50 the following:
```idx = pd.date_range("2017-01-01", periods=8760, freq="60T")```
Instead would become:
```idx = pd.date_range("2017-01-01", periods=8760, freq="60min")```

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #208 

replaced deprecated `freq` arguments "T" and "H" with "min" and "h"

### Test files

run the `run_tests.bat` file after compiling, and see that all the unit tests pass, and no warnings are produced.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Review by jamesramsden-bh — APPROVED** [review]
Tested via unit tests, all tests passing and warnings now removed.

**Comment by Tom-Kingstone** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
